tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                outline: "#6f797c",
                "on-surface": "#181c20",
                "surface-container-low": "#f1f4f9",
                primary: "#004655",
                "primary-container": "#005f73",
                "tertiary-fixed-dim": "#c4c7ca",
                "error-container": "#ffdad6",
                "inverse-primary": "#8bd1e8",
                "on-tertiary": "#ffffff",
                "secondary-fixed-dim": "#afcdc7",
                "on-background": "#181c20",
                "surface-variant": "#e0e3e8",
                "primary-fixed": "#b2ebff",
                "secondary-container": "#cae9e3",
                "surface-container-highest": "#e0e3e8",
                "on-primary": "#ffffff",
                "on-primary-container": "#91d7ee",
                secondary: "#48645f",
                "on-tertiary-container": "#c9cdd0",
                "inverse-surface": "#2d3135",
                "outline-variant": "#bfc8cc",
                "on-secondary-fixed-variant": "#304c47",
                "on-secondary-container": "#4e6a65",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-fixed-variant": "#43474a",
                "on-primary-fixed-variant": "#004e5f",
                "on-secondary-fixed": "#03201c",
                "surface-tint": "#13677b",
                "on-primary-fixed": "#001f27",
                "secondary-fixed": "#cae9e3",
                "surface-dim": "#d7dadf",
                "on-error-container": "#93000a",
                "on-error": "#ffffff",
                "on-secondary": "#ffffff",
                surface: "#f7f9ff",
                "on-surface-variant": "#3f484c",
                "surface-container-high": "#e5e8ee",
                background: "#f7f9ff",
                "surface-bright": "#f7f9ff",
                "inverse-on-surface": "#eef1f6",
                "primary-fixed-dim": "#8bd1e8",
                "on-tertiary-fixed": "#181c1e",
                "tertiary-fixed": "#e0e3e6",
                error: "#ba1a1a",
                tertiary: "#3c4042",
                "tertiary-container": "#53575a",
                "surface-container": "#ebeef3",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                gutter: "16px",
                "max-width": "1280px",
                unit: "4px",
                "margin-desktop": "48px",
                "margin-mobile": "16px",
            },
            fontFamily: {
                "body-lg": ["Hanken Grotesk"],
                "label-md": ["Hanken Grotesk"],
                "headline-md": ["Space Grotesk"],
                "headline-lg-mobile": ["Space Grotesk"],
                "label-sm": ["Hanken Grotesk"],
                "body-md": ["Hanken Grotesk"],
                "headline-xl": ["Space Grotesk"],
                "headline-lg": ["Space Grotesk"],
            },
            fontSize: {
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
                "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
                "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
                "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
                "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
                "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
            },
        },
    },
};